name: mesmo
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.1
  - attrs=21.4.0
  - boost-cpp=1.70.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.5.18.1
  - cairo=1.16.0
  - certifi=2022.5.18.1
  - cffi=1.15.0
  - cfitsio=3.470
  - charset-normalizer=2.0.12
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - contextily=1.2.0
  - cryptography=37.0.2
  - curl=7.83.1
  - cvxpy=1.2.1
  - cvxpy-base=1.2.1
  - cycler=0.11.0
  - ecos=2.0.10
  - expat=2.4.8
  - fontconfig=2.13.94
  - fonttools=4.33.3
  - freetype=2.10.4
  - freexl=1.0.6
  - geographiclib=1.52
  - geopy=2.2.0
  - geos=3.8.0
  - geotiff=1.7.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.70.2
  - glib-tools=2.70.2
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.3
  - joblib=1.1.0
  - jpeg=9e
  - json-c=0.13.1
  - kealib=1.4.14
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.83.1
  - libcxx=14.0.3
  - libdap4=3.19.1
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgdal=3.0.2
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libglib=2.70.2
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libpq=12.9
  - libspatialite=4.3.0a
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzlib=1.2.11
  - llvm-openmp=14.0.4
  - lz4-c=1.9.3
  - matplotlib-base=3.5.2
  - mercantile=1.2.1
  - munkres=1.1.4
  - ncurses=6.3
  - numpy=1.22.4
  - openjpeg=2.4.0
  - openssl=1.1.1o
  - osqp=0.6.2.post0
  - packaging=21.3
  - pandas=1.4.2
  - pcre=8.45
  - pillow=9.1.1
  - pip=22.1.1
  - pixman=0.38.0
  - poppler=0.89.0
  - poppler-data=0.4.11
  - proj=6.2.1
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2022.1
  - qdldl-python=0.1.5
  - rasterio=1.2.10
  - readline=8.1
  - requests=2.27.1
  - scipy=1.8.1
  - scs=3.2.0
  - setuptools=62.3.2
  - six=1.16.0
  - snuggs=1.4.7
  - sqlite=3.38.5
  - tiledb=2.9.1
  - tk=8.6.12
  - unicodedata2=14.0.0
  - urllib3=1.26.9
  - wheel=0.37.1
  - xerces-c=3.2.3
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xyzservices=2022.4.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - aiohttp==3.8.1
    - aiohttp-cors==0.7.0
    - aiosignal==1.2.0
    - async-timeout==4.0.2
    - bleach==5.0.0
    - blessed==1.19.1
    - bokeh==2.4.3
    - cachetools==5.1.0
    - colorcet==3.0.0
    - colorful==0.5.4
    - coverage==6.4
    - deprecated==1.2.13
    - dill==0.3.5.1
    - distlib==0.3.4
    - dss-python==0.10.7.post1
    - dynaconf==3.1.8
    - filelock==3.7.0
    - flake8==4.0.1
    - frozenlist==1.3.0
    - future==0.18.2
    - google-api-core==2.8.0
    - google-auth==2.6.6
    - googleapis-common-protos==1.56.1
    - gpustat==1.0.0b1
    - grpcio==1.43.0
    - gurobipy==9.5.1
    - h5py==3.7.0
    - holoviews==1.14.9
    - hvplot==0.8.0
    - importlib-metadata==4.11.4
    - importlib-resources==5.7.1
    - iniconfig==1.1.1
    - jinja2==3.1.2
    - jsonschema==4.5.1
    - kaleido==0.2.1
    - markdown==3.3.7
    - markupsafe==2.1.1
    - mccabe==0.6.1
    - msgpack==1.0.3
    - multidict==6.0.2
    - multimethod==1.8
    - natsort==8.1.0
    - networkx==2.8.2
    - nvidia-ml-py3==7.352.0
    - opencensus==0.9.0
    - opencensus-context==0.1.2
    - opencv-python-headless==4.5.5.64
    - opendssdirect-py==0.6.1
    - panel==0.13.1
    - param==1.12.1
    - parameterized==0.8.1
    - platformdirs==2.5.2
    - plotly==5.8.0
    - pluggy==1.0.0
    - prometheus-client==0.13.1
    - protobuf==3.20.1
    - psutil==5.9.1
    - psychrolib==2.5.0
    - pvlib==0.9.1
    - py==1.11.0
    - py-spy==0.3.12
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.8.0
    - pyct==0.4.8
    - pyflakes==2.4.0
    - pyrsistent==0.18.1
    - pytest==7.1.2
    - pytest-cov==3.0.0
    - pytest-subtests==0.8.0
    - pyviz-comms==2.2.0
    - pyyaml==6.0
    - ray==1.12.1
    - redis==4.3.1
    - rsa==4.8
    - smart-open==6.0.0
    - tenacity==8.0.1
    - tomli==2.0.1
    - tornado==6.1
    - tqdm==4.64.0
    - typing-extensions==4.2.0
    - virtualenv==20.14.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - wrapt==1.14.1
    - yarl==1.7.2
    - zipp==3.8.0
