name: mesmo
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.3.0
  - attrs=21.2.0
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - cfitsio=4.0.0
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=8.0.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - contextily=1.2.0
  - cryptography=35.0.0
  - curl=7.79.1
  - cvxpy=1.1.17
  - cvxpy-base=1.1.17
  - cycler=0.11.0
  - expat=2.4.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - freexl=1.0.6
  - geographiclib=1.52
  - geopy=2.2.0
  - geos=3.10.0
  - geotiff=1.7.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=69.1
  - idna=3.1
  - jbig=2.1
  - joblib=1.1.0
  - jpeg=9d
  - json-c=0.15
  - kealib=1.4.14
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.79.1
  - libdap4=3.20.6
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgdal=3.3.3
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.43.0
  - libnsl=2.0.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libpq=13.3
  - librttopo=1.1.0
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libwebp-base=1.2.1
  - libxcb=1.13
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - matplotlib-base=3.4.3
  - mercantile=1.2.1
  - ncurses=6.2
  - nspr=4.32
  - nss=3.71
  - numpy=1.21.4
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - osqp=0.6.2
  - pandas=1.3.4
  - pcre=8.45
  - pillow=8.3.2
  - pip=21.3.1
  - pixman=0.40.0
  - poppler=21.09.0
  - poppler-data=0.4.11
  - postgresql=13.3
  - proj=8.1.1
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyopenssl=21.0.0
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.3
  - qdldl-python=0.1.5
  - rasterio=1.2.10
  - readline=8.1
  - requests=2.26.0
  - scipy=1.7.1
  - scs=3.0.0
  - setuptools=58.5.3
  - six=1.16.0
  - snuggs=1.4.7
  - sqlite=3.36.0
  - tiledb=2.3.4
  - tk=8.6.11
  - tornado=6.1
  - tzcode=2021e
  - tzdata=2021e
  - urllib3=1.26.7
  - wheel=0.37.0
  - xerces-c=3.2.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2021.11.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - aiohttp==3.8.0
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - aiosignal==1.2.0
    - async-timeout==4.0.0
    - bleach==4.1.0
    - blessed==1.19.0
    - bokeh==2.4.1
    - cachetools==4.2.4
    - colorcet==2.0.6
    - colorful==0.5.4
    - dill==0.3.4
    - dss-python==0.10.7.post1
    - ecos==2.0.7.post1
    - filelock==3.3.2
    - frozenlist==1.2.0
    - future==0.18.2
    - google-api-core==2.2.2
    - google-auth==2.3.3
    - googleapis-common-protos==1.53.0
    - gpustat==1.0.0b1
    - grpcio==1.41.1
    - gurobipy==9.1.2
    - h5py==3.5.0
    - hiredis==2.0.0
    - holoviews==1.14.6
    - hvplot==0.7.3
    - importlib-resources==5.4.0
    - jinja2==3.0.2
    - jsonschema==4.2.1
    - kaleido==0.2.1
    - markdown==3.3.4
    - markupsafe==2.0.1
    - msgpack==1.0.2
    - multidict==5.2.0
    - multimethod==1.6
    - natsort==8.0.0
    - networkx==2.6.3
    - nvidia-ml-py3==7.352.0
    - opencensus==0.8.0
    - opencensus-context==0.1.2
    - opencv-python==4.5.4.58
    - opendssdirect-py==0.6.1
    - packaging==21.2
    - panel==0.12.4
    - param==1.12.0
    - parameterized==0.8.1
    - plotly==5.3.1
    - prometheus-client==0.12.0
    - protobuf==3.19.1
    - psutil==5.8.0
    - psychrolib==2.5.0
    - pvlib==0.9.0
    - py-spy==0.3.10
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyct==0.4.8
    - pyparsing==2.4.7
    - pyrsistent==0.18.0
    - pyviz-comms==2.1.0
    - pyyaml==6.0
    - ray==1.8.0
    - redis==3.5.3
    - rsa==4.7.2
    - tenacity==8.0.1
    - tqdm==4.62.3
    - typing-extensions==3.10.0.2
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - yarl==1.7.2
    - zipp==3.6.0
