# Configuration default values.
# - These values can be overwritten with a custom `config.yml` in the repository base directory.
# - In the path settings, `./` denotes the repository base directory and is replaced upon loading.
paths:
  additional_data: []
  ignore_data_folders: []
  data: ./data
  database: ./data/database.sqlite
  results: ./results
  cobmo_additional_data: []
multiprocessing:
  run_parallel: false  # Disabled by default to avoid unexpected issues.
caching:
  enable: false  # If false, no cache is created. Disabled by default to avoid unexpected issues.
  reset_cache: false  # If true, reset the cache on each restart of MESMO, to incorporate changes in the database.
  expiry_time: 3600  # Expiry time of the cache, in seconds.
  get_building_model: true
optimization:
  solver_interface:  # If 'cvxpy', will use CVXPY. If not defined, will use direct solver interfaces.
  solver_name: gurobi  # Choices: 'gurobi' or any valid solver name for CVXPY.
  time_limit:  # Solver time limit in seconds. Infinite if not defined. Only for Gurobi / CPLEX.
  show_solver_output: true  # If True, activate verbose solver output.
tests:
  scenario_name: singapore_6node  # Defines scenario which is considered in tests.
logs:
  level: info  # Choices: `debug`, `info`, `warn`.
  format: '%(asctime)s | %(levelname)s | %(message)s'
plots:
  matplotlib_style: seaborn-colorblind
  matplotlib_colormap: viridis_r
  matplotlib_font_family: ['Arial', 'Helvetica']
  matplotlib_figure_size: [7.0, 4.0]
  plotly_font_family: Arial
  plotly_font_size: 15
  plotly_figure_width: 1000
  plotly_figure_height: 500
  file_format: png
  add_basemap: false  # If True, add basemap layer to grid plots for orientation. Requires installation of `contextily`.
  show_basemap_attribution: false # If True, show copyright notice for basemap.
